/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Drawer: typeof import('./src/components/Drawer/index.vue')['default']
    Echarts: typeof import('./src/components/Echarts/index.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    SwitchContent: typeof import('./src/components/SwitchContent/index.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/index.vue')['default']
  }
}
